# File: client/Dockerfile
# Stage 1: Build
FROM node:20 as build
ARG VITE_API_BASE_URL=http://localhost:8000
WORKDIR /app

COPY client/package*.json ./
RUN npm install

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
COPY client/ ./
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
# COPY client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]