services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.api
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: dockerfile.client
      args:
        VITE_API_BASE_URL: http://backend:8000
    ports:
      - "80:80"
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    