services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.api
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    expose:
      - "8000"

  frontend:
    build:
      context: .
      dockerfile: dockerfile.client
      args:
        VITE_API_BASE_URL: /api
    expose:
      - "80"
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    